language: ruby
cache: bundler

services:
  - mysql

addons:
  postgresql: '9.4'

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

  - cp config/db.travis-ci.yml config/db.yml
  - mysql -e 'CREATE DATABASE metaflop_test;'

script: bundle exec rspec -f d spec
