metaflop:
  preview_height: 315
  preview_width: 340

  preview_single:
    generate: |
      \documentclass[a4paper]{report}\
      \usepackage{color}\
      \definecolor{bgcolor}{rgb}{0.9,1,0.843}\
      \begin{document}\
      \pagestyle{empty}\
      \font\big=font at 56pt\
      \noindent\
      \big\
      \put(-55,-50){\colorbox{bgcolor}{\makebox(150,150){}}}\
      \put(2,0){{{text}}}\
      \thinlines\
      \end{document}

    convert_custom: dvigif -D 200 font.dvi -o font.gif > /dev/null && convert font.gif -resize '{{width}}'

  preview_chart:
    generate: latex -output-format=dvi -jobname=font "\\documentclass[a4paper]{report} \begin{document} \pagestyle{empty} \font\big=font at 22pt \noindent \big \begin{center} \setlength{\tabcolsep}{18pt} \begin{tabular}{ c  c  c  c  c  c  c }  A & B & C & D & E & F & G \\ \cr   &   &   &   &   &   &   \\ \cr   &   &   &   &   &   &   \\ \cr H & I & J & K & L & M & N \\ \cr   &   &   &   &   &   &   \\ \cr   &   &   &   &   &   &   \\ \cr  O & P & Q & R & S & T & U  \\  \cr  &   &   &   &   &   &   \\ \cr  &   &   &   &   &   &   \\ \cr  V & W & X & Y & Z   \\ \cr   &   &   &   &   &   &   \\ \cr   &   &   &   &   &   &   \\ \cr a & b & c & d & e & f & g \\ \cr   &   &   &   &   &   &   \\ \cr   &   &   &   &   &   &   \\ \cr h & i & j & k & l & m & n \\ \cr   &   &   &   &   &   &   \\ \cr   &   &   &   &   &   &   \\ \cr o & p & q & r & s & t & u \\ \cr   &   &   &   &   &   &   \\ \cr   &   &   &   &   &   &   \\ \cr v & w & x & y & z & . & ! \\ \cr   &   &   &   &   &   &   \\ \cr   &   &   &   &   &   &   \\ \cr \end{tabular}  \end{center} \end{document}"

    convert_custom: dvigif -D 200 font.dvi -o font.gif >> /dev/null && convert font.gif -trim +repage -resize 'x{{height}}'

  preview_typewriter:
    generate: latex -output-format=dvi -jobname=font "\\documentclass[a4paper]{report} \begin{document} \pagestyle{empty} \font\big=font at 20pt \noindent \big \begin{flushleft}{{text}} \end{flushleft} \end{document}"

    convert_custom: dvigif -D 200 font.dvi -o font.gif >> /dev/null && convert font.gif -trim +repage -resize '675'

  font_otf: 'perl mf2pt1.pl --comment="Copyright (C) 2012 by Metaflop - Simon Egli, Marco Mueller. http://www.metaflop.com. All rights reserved. License: A copy of the End-User License Agreement to this font software can be found online at http://www.metaflop.com." --family={{fontface}} --nofixedpitch --fullname="{{fontface}} {{font_hash}}" --name="{{fontface}}-{{font_hash}}" --weight={{font_hash}} font.mf'

projects:
  lovehate: 
    description: 'all the works of <a href="http://www.christianvetter.ch" target="_blank">christian vetter</a> gravitate around the topic of painting and generating new possibilities of perception: how can a work stay as an ornament, completely abstract, and in the same time produce a meaning, a content? christian vetter uses <a href="/fonts/adjuster">mf adjuster</a> as a structure, as a construction kit in order to build autonomous in-between spaces. this time, as an exception in his work, the meaning of the words is not secondary, but the main focus stays on the affiliation of the font to image. the phrase structure stays, one word or one letter changes which creates not only a different space disposition but simultaneously a new meaning.'
    images:
      - lovehate2-01.png
      - lovehate2-02.png
      - lovehate2-03.png
      - lovehate2-04.png
      - lovehate2-05.png
      - lovehate2-06.png
      - lovehate2-07.png

fonts:
  bespoke: 
    description: mf bespoke is geared to contemporary and simply constructed sans serif fonts. the geometrical construction is based on a rectangle and can easily be transformed by means of the parameters <em>increase</em> and <em>superness</em> to an octagon. the parameter <em>superness</em> generates in its lower values unusual and playful results of curves.<br /> <a href="/modulator?fontface=Bespoke">mf bespoke</a> consists of adjustable parameters grouped in classes of dimension, proportion and shape. this wide range enables you to create sans serif fonts for a broad variety of use. for a classic and elegant version just add a bit of <em>contrast</em> to the default settings.
    images:
      - bespoke1-01.png
      - bespoke1-02.png
      - bespoke1-03.png
  adjuster: 
    description: 'mf adjuster is a font with a very basic form, plain architectural, highly functional, almost crystalline. it follows a strict grid and a simple no-curves-policy and comes along with a rather reduced set of parameters. although the dimension and proportion of mf <a href="/modulator?fontface=Adjuster">mf adjuster</a> can vary, its sophistication derives from the pen parameter: you can choose from <em>circle</em>, <em>square</em> or <em>razor</em>.'
    images:
      - adjuster1-01.png
      - adjuster1-02.png
      - adjuster1-03.png

