metaflop:
  preview_width: 340

  # the "latex" sections are mustachified with <% %> tags instead of std {{}}
  preview_single:
    latex: |
      \documentclass[a4paper]{report}
      \usepackage{color}
      \definecolor{bgcolor}{rgb}{0.9,1,0.843}
      \begin{document}
      \pagestyle{empty}
      \font\big=font at 56pt
      \noindent
      \big
      \put(-55,-50){\colorbox{bgcolor}{\makebox(150,150){}}}
      \put(-77,2){\parbox[b]{200pt}{\centerline{<% text %>}}}
      \thinlines
      \end{document}

  preview_chart:
    latex: |
      \documentclass[a4paper]{report}
      \usepackage{color}
      \definecolor{bgcolor}{rgb}{0.9,1,0.843}
      \begin{document}
      \pagestyle{empty}
      \font\big=font at 9pt
      \noindent
      \big
      \put(-2,-97){\colorbox{bgcolor}{\makebox(200,200){}}}
      \begin{minipage}[-50,-50]{200pt}
      \begin{center}
      \setlength{\tabcolsep}{10pt}
      \begin{tabular}{ c  c  c  c  c  c  c }
      A & B & C & D & E & F & G
      \cr H & I & J & K & L & M & N
      \cr O & P & Q & R & S & T & U
      \cr V & W & X & Y & Z
      \cr a & b & c & d & e & f & g
      \cr h & i & j & k & l & m & n
      \cr o & p & q & r & s & t & u
      \cr v & w & x & y & z
      \end{tabular}
      \end{center}
      \end{minipage}
      \end{document}

  preview_typewriter:
    latex: |
      \documentclass[a4paper]{report}
      \usepackage{color}
      \definecolor{bgcolor}{rgb}{0.9,1,0.843}
      \begin{document}
      \pagestyle{empty}
      \font\big=font at 16pt
      \noindent
      \big
      \setlength{\fboxrule}{5pt}
      \setlength{\fboxsep}{5pt}
      \put(-55,-50){\fcolorbox{bgcolor}{bgcolor}{\parbox{300pt}{<% text %>}}}
      \end{document}

  font_otf: 'perl mf2pt1.pl --encoding=t1 --comment="Copyright (C) 2012 by Metaflop - Simon Egli, Marco Mueller. http://www.metaflop.com. All rights reserved. License: A copy of the End-User License Agreement to this font software can be found online at http://www.metaflop.com." --family={{fontface}} --nofixedpitch --fullname="{{fontface}} {{font_hash}}" --name="{{fontface}}-{{font_hash}}" --weight={{font_hash}} font.mf'

  font_web: sfnt2woff font.otf && ttf2eot font.ttf > font.eot

metafonts:
  bespoke: 
    description: mf bespoke is geared to contemporary and simply constructed sans serif fonts. the geometrical construction is based on a rectangle and can easily be transformed by means of the parameters <em>increase</em> and <em>superness</em> to an octagon. the parameter <em>superness</em> generates in its lower values unusual and playful results of curves.<br /> <a href="/modulator?fontface=Bespoke">mf bespoke</a> consists of adjustable parameters grouped in classes of dimension, proportion and shape. this wide range enables you to create sans serif fonts for a broad variety of use. for a classic and elegant version just add a bit of <em>contrast</em> to the default settings.
    images:
      - bespoke1-01.png
      - bespoke1-02.png
      - bespoke1-03.png
      - bespoke1-04.png
      - bespoke1-05.png
      - bespoke1-06.png
      - bespoke1-07.png
      - bespoke2-01.png
      - bespoke2-02.png
      - bespoke2-03.png
      - bespoke2-04.png
      - bespoke2-05.png
      - bespoke2-06.png
    subimages:
      -
        - bespoke-derivations-01.png
        - W2wMVl1oOf
      -
        - bespoke-derivations-02.png
        - wEEJXpb_F_
      -
        - bespoke-derivations-03.png
        - X_nuDV5EKb
      -
        - bespoke-derivations-04.png
        - xQZl0I4bG4
      -
        - bespoke-derivations-05.png
        - bBv88L09e8
      -
        - bespoke-derivations-06.png
        - f0ySyHr68Q
      -
        - bespoke-derivations-07.png
        - bQCd3GYPgX
      -
        - bespoke-derivations-08.png
        - Hb-V8s8C70
      -
        - bespoke-derivations-09.png
        - jVzgqoraQu
      -
        - bespoke-derivations-10.png
        - L9JtCtna31
      -
        - bespoke-derivations-11.png
        - tRp6NK0eyw
      -
        - bespoke-derivations-12.png
        - UcH5rxsNVi

  adjuster: 
    description: 'mf adjuster is a font with a very basic form, plain architectural, highly functional, almost crystalline. it follows a strict grid and a simple no-curves-policy and comes along with a rather reduced set of parameters. although the dimension and proportion of mf <a href="/modulator?fontface=Adjuster">mf adjuster</a> can vary, its sophistication derives from the pen parameter: you can choose from <em>circle</em>, <em>square</em> or <em>razor</em>.'
    images:
      - adjuster1-01.png
      - adjuster1-02.png
      - adjuster1-03.png
      - adjuster1-04.png
      - adjuster1-05.png
      - adjuster1-06.png
      - adjuster1-07.png
      - adjuster2-01.png
      - adjuster2-02.png
      - adjuster2-03.png
      - adjuster2-04.png
      - adjuster2-05.png
    subimages:
      -
        - adjuster-derivations-01.png
        - QLiweKaNal
