metafonts:
  adjuster:
    description: <a href="/modulator?fontface=Adjuster">MF Adjuster</a>, a basic form,
      highly functional, almost crystalline. It follows a strict grid and a simple no-curves policy
      and it comes along with a reduced set of parameters.
      The font's sophistication derives from the angle and pen parameter (circle, square or razor).
      The font encoding of MF Adjuster covers 256 characters supporting many european languages
      with latin writing.
    type_designer:
      -
        name: Marco Müller
        url: http://www.marco-mueller.com/
      -
        name: Simon Egli
        url: http://www.simonegli.com/
    year: 2012–2014
    encoding: T1
    source_code:
      -
        title: Github
        url: https://github.com/metaflop/metaflop-font-adjuster
    images:
      -
        - adjuster1-01.svg
        -
      -
        - adjuster1-02.svg
        -
      -
        - adjuster1-03.svg
        -
      -
        - adjuster1-04.svg
        - The 256 characters of T1 font encoding.
      -
        - adjuster1-05.svg
        - MF Adjuster supporting many european languages with latin writing.
      -
        - adjuster1-06.png
        - Transformation of the Angle parameter.
      -
        - adjuster2-01.png
        - Angle transformation from 90 to 15 degree and vice versa.
      -
        - adjuster2-02.png
        - Pen Width transformation from 2.0 to 0.05 points and vice versa.
      -
        - adjuster2-03.png
        - Unit width transformation from 0.2 to 5.0 points.
      -
        - adjuster2-04.png
        - Unit width transformation from 5.0 to 0.2 points.
      -
        - adjuster2-05.png
        - Pen Razor transformation from 0 to 45 degree and vice versa.
    subimages:
      -
        - adjuster-derivations-01.svg
        - 4pY8SPVUeO
      -
        - adjuster-derivations-02.svg
        - GfXF00-goL
      -
        - adjuster-derivations-03.svg
        - pQkUOJOPk8
      -
        - adjuster-derivations-04.svg
        - WitXxEC_wq
      -
        - adjuster-derivations-05.svg
        - 19mOboz6Sq
      -
        - adjuster-derivations-06.svg
        - B_DF7u3XWz
      -
        - adjuster-derivations-07.svg
        - JgRFUo8ZJV
      -
        - adjuster-derivations-08.svg
        - BL4uWv2Vdt
      -
        - adjuster-derivations-09.svg
        - xo_LzNRVdV
      -
        - adjuster-derivations-10.svg
        - poimn57bWc
      -
        - adjuster-derivations-11.svg
        - N-SDv-KkDl
      -
        - adjuster-derivations-12.svg
        - IVhW3c2vuS
  bespoke:
    description: <a href="/modulator?fontface=Bespoke">MF Bespoke</a> is geared to simply
      constructed sans serif fonts. This metafont consists of 14 adjustable parameters grouped
      in classes of dimension, proportion and shape.
      By using this range of parameters a high variety of derivates can be achieved.
      The T1 encoding of MF Bespoke covers 256 characters supporting many
      european languages with latin writing.
    type_designer:
      -
        name: Marco Müller
        url: http://www.marco-mueller.com/
      -
        name: Simon Egli
        url: http://www.simonegli.com/
    year: 2012–2016
    encoding: 't1'
    source_code:
      -
        title: Github
        url: https://github.com/metaflop/metaflop-font-bespoke"
    images:
      -
        - bespoke1-01.svg
        -
      -
        - bespoke1-02.svg
        -
      -
        - bespoke1-03.svg
        -
      -
        - bespoke1-04.svg
        - MF Bespoke supporting many european languages with latin writing.
      -
        - bespoke1-05.svg
        -
      -
        - bespoke1-06.png
        -
      -
        - bespoke2-01.png
        - Superness curve transformation from 1.0 to 0.3 and vice versa.
      -
        - bespoke2-02.png
        - Contrast transformation from 18 to 1 and vice versa.
      -
        - bespoke2-03.png
        - Horizontal and vertical increase transformation from 1.0 to 0.0 points and vice versa.
      -
        - bespoke2-04.png
        - Unit width transformation from 0.2 to 5.0 points.
      -
        - bespoke2-05.png
        - Unit width transformation from 5.0 to 0.2 points.
      -
        - bespoke2-06.png
        - Horizontal and vertical increase transformation from 1.0 to 0.0 points and vice versa.
    subimages:
      -
        - bespoke-derivations-01.svg
        - 4WJYLMoYJb
      -
        - bespoke-derivations-02.svg
        - spoqlZV8n3
      -
        - bespoke-derivations-03.svg
        - WQpfAjTK7l
      -
        - bespoke-derivations-04.svg
        - VHvNIzZuE9
      -
        - bespoke-derivations-05.svg
        - yKLK4x6MHp
      -
        - bespoke-derivations-06.svg
        - 2Llq27N0HS
      -
        - bespoke-derivations-07.svg
        - jbDcNNx0Ss
      -
        - bespoke-derivations-08.svg
        - sN99ysuCfX
      -
        - bespoke-derivations-09.svg
        - RXs7iBJfQX
      -
        - bespoke-derivations-10.svg
        - ekVa5bxevw
      -
        - bespoke-derivations-11.svg
        - FfcB5XuDKR
      -
        - bespoke-derivations-12.svg
        - JLROi5SwqW
      -
        - bespoke-derivations-13.svg
        - Mg__1hCUUp
  fetamont:
    description: <a href="/modulator?fontface=Fetamont">MF Fetamont</a> is an extended version of
      Knuth's rounded elliptical logo font.
      The 11 parameters, including superness, slanting and randomness,
      enlarge the logo font to a complete typeface with a high variety of derivates.
      The font covers capital letters and small caps with a T1 encoding of 256
      characters supporting many european languages with latin writing.
    type_designer:
      -
        name: Linus Romer
        url: http://www.ctan.org/author/romer
    year: 2014
    encoding: T1
    source_code:
      -
        title: Github
        url: https://github.com/metaflop/metaflop-font-fetamont
      -
        title: CTAN
        url: http://www.ctan.org/tex-archive/fonts/fetamont
    images:
      -
        - fetamont-01.svg
        -
      -
        - fetamont-02.svg
        - The 256 characters of T1 font encoding.
      -
        - fetamont-03.svg
        -
      -
        - fetamont-04.svg
        - MF Fetamont supporting many european languages with latin writing.
      -
        - fetamont-05.svg
        -
      -
        - fetamont-06.svg
        -
    subimages:
      -
        - fetamont-derivations-01.svg
        - GkBrVZN_iX
      -
        - fetamont-derivations-02.svg
        - MfkdNdMDDn
      -
        - fetamont-derivations-03.svg
        - dl7Ht74V5u
      -
        - fetamont-derivations-04.svg
        - LkeR_2xby-
      -
        - fetamont-derivations-05.svg
        - PP_OiCwdeP
      -
        - fetamont-derivations-06.svg
        - 27bdRg9sxs
      -
        - fetamont-derivations-07.svg
        - 9ExkzVmc3w
      -
        - fetamont-derivations-08.svg
        - -VD4YZ2DoE
      -
        - fetamont-derivations-09.svg
        - hCBJISerqx
      -
        - fetamont-derivations-10.svg
        - Lib0ZSdIQq
      -
        - fetamont-derivations-11.svg
        - lIyb2HtLTh
      -
        - fetamont-derivations-12.svg
        - e93KUT9DBj
      -
        - fetamont-derivations-13.svg
        - 6vxhO7I2He
      -
        - fetamont-derivations-14.svg
        - aqgUyrHqrz
      -
        - fetamont-derivations-15.svg
        - -G_AJAvhEX
      -
        - fetamont-derivations-16.svg
        - dFcZJbTYmO
      -
        - fetamont-derivations-17.svg
        - MelgMG3dUD
      -
        - fetamont-derivations-18.svg
        - ei9rUTPryF
      -
        - fetamont-derivations-19.svg
        - dJCvFHU3OR

  funtauna:
    description: <a href="/modulator?fontface=Funtauna">MF Funtauna</a> is a
      rectangular slab-serif font similar to the Georg Trump's City (1930) or
      Adrian Frutiger's Algol (1963) typefaces. Its geometric structure of
      right angles and opposing round corners hints at the early 20th century
      machine age and industrial times. The serifs and superness parameters
      enable variations of square, sans-serif or even hairline serif fonts. The
      unicode font encoding of MF Funtauna covers over 360 characters
      supporting many European languages with latin writing.
    type_designer:
      -
        name: Linus Romer
        url: http://www.ctan.org/author/romer
    year: 2017–2018
    encoding: unicode
    source_code:
      -
        title: Github
        url: https://github.com/metaflop/metaflop-font-funtauna
      -
        title: Font Library
        url: https://fontlibrary.org/en/font/funtauna
    images:
      -
        - funtauna-01.svg
        -
      -
        - funtauna-02.svg
        -
      -
        - funtauna-03.svg
        -
      -
        - funtauna-04.svg
        -
      -
        - funtauna-05.svg
        - mf funtauna supporting many european languages with latin writing.
      -
        - funtauna-06.svg
        - selection of characters from unicode font encoding.
    subimages:
      -
        - funtauna-derivations-01.svg
        - GTWpMn5z3M
      -
        - funtauna-derivations-02.svg
        - Julk1hfTY6
      -
        - funtauna-derivations-03.svg
        - n_5ihPGn6H
      -
        - funtauna-derivations-04.svg
        - 2Hxp8SiPeJ
      -
        - funtauna-derivations-05.svg
        - d5Gspby3UU
      -
        - funtauna-derivations-06.svg
        - cC8kv874is
      -
        - funtauna-derivations-07.svg
        - RRTjhGIiQR
      -
        - funtauna-derivations-08.svg
        - jiV3-m29bU
      -
        - funtauna-derivations-09.svg
        - --u1GVnJpC
      -
        - funtauna-derivations-10.svg
        - _cHlwGdwVL
      -
        - funtauna-derivations-11.svg
        - xaj6S8CbTg
      -
        - funtauna-derivations-12.svg
        - Xxo7ME1nfa
      -
        - funtauna-derivations-13.svg
        - cZSA-Qkr68
      -
        - funtauna-derivations-14.svg
        - GWJAIjR4H0
      -
        - funtauna-derivations-15.svg
        - gNNHl_TXtB
      -
        - funtauna-derivations-16.svg
        - dKLQ5X1bRI
      -
        - funtauna-derivations-17.svg
        - zVDKB5SqfO
