showcases:
  electronic_superhighway:
    title: Electronic Superhighway
    description: <p><a
      href="http://www.whitechapelgallery.org/about/blog/top-10-electronic-superhighway/"
      target="_blank">Electronic Superhighway</a> features over 100 works of
      art that show the impact of computer and internet technologies on artists
      from the mid-1960s to the present day.</p>

      <p>The London based <a href="http://www.julia.uk.com/"
      target="_blank">design studio Julia</a> created the catalogue for the <a
      href="http://www.whitechapelgallery.org/" target="_blank">Whitechapel
      Gallery</a>’s exhibition, taking its central theme of the online and
      digital worlds and translating it into designs that are based around MF
      Bespoke. By mixing different font variations into an equal text block it
      references the way code is written by programmers.</p>
    design: <a href="http://www.julia.uk.com/" target="_blank">Julia</a>
    year: 2016
    font: <a href="/metafonts/bespoke">MF Bespoke</a>
    images:
      - Julia-Electronic_Superhighway-01.jpg
      - Julia-Electronic_Superhighway-02.jpg
      - Julia-Electronic_Superhighway-03.jpg
      - Julia-Electronic_Superhighway-04.jpg
      - Julia-Electronic_Superhighway-05.jpg
      - Julia-Electronic_Superhighway-06.jpg
      - Julia-Electronic_Superhighway-07.jpg
      - Julia-Electronic_Superhighway-08.jpg
      - Julia-Electronic_Superhighway-09.jpg
      - Julia-Electronic_Superhighway-10.jpg
      - Julia-Electronic_Superhighway-11.jpg
      - Julia-Electronic_Superhighway-12.jpg
      - Julia-Electronic_Superhighway-13.jpg
      - Julia-Electronic_Superhighway-14.jpg
      - Julia-Electronic_Superhighway-15.jpg
      - Julia-Electronic_Superhighway-16.jpg
      - Julia-Electronic_Superhighway-17.jpg
      - Julia-Electronic_Superhighway-18.jpg
      - Julia-Electronic_Superhighway-19.jpg
      - Julia-Electronic_Superhighway-20.jpg
      - Julia-Electronic_Superhighway-21.jpg

  off_grid:
    title: Off Grid
    description: <p>Off Grid features interdisciplinary artists and graphic
      designers in an exhibition that was originally shown at South Block
      Glasgow as part of <a href="http://graphicdesignfestivalscotland.com"
      target="_blank">Graphic Design Festival Scotland</a> 2015 before being
      invited to Nancy, France, where it was shown at <a
      href="http://mymonkey.fr" target="_blank">Galerie My Monkey</a>.</p>

      <p>The Glasgow based <a href="http://warriorsstudio.com/"
      target="_blank">Warriors Studio</a> created a clear and reduced visual
      identity, using a medium weight of MF Bespoke for the exhibition leaflet
      and displays.</p>

    design: <a href="http://warriorsstudio.com" target="_blank">Warriors Studio</a>
    year: 2015
    font: <a href="/metafonts/bespoke">MF Bespoke</a>
    images:
      - warriors-studio-off-grid_01.jpg
      - warriors-studio-off-grid_02.jpg
      - warriors-studio-off-grid_03.jpg
      - warriors-studio-off-grid_04.jpg
      - warriors-studio-off-grid_05.jpg
      - warriors-studio-off-grid_06.jpg
      - warriors-studio-off-grid_07.jpg
      - warriors-studio-off-grid_08.jpg
      - warriors-studio-off-grid_09.jpg

  staging_disorder:
    title: Staging Disorder
    description: <p><a href="http://www.arts.ac.uk/lcc/" target="_blank">London
      College of Communication</a>’s exhibition of <a
      href="http://www.designweek.co.uk/issues/26-january-1-february-2015/staging-disorder-at-lcc/"
      target="_blank">Staging Disorder</a> examines the work of seven
      photographers each interested in the environments used to simulate and
      prepare for modern warfare.</p>

      <p>The idea of a constructed reality has been reflected in the exhibition
      designed by <a href="http://www.studiohato.com/" target="_blank">Studio
      Hato</a>, which includes unfinished paint edges surrounding the
      photographs, a paper-and-tape-effect design used to present the artists’
      credits. A version with reduced superness for MF Bespoke was used,
      resulting in a font with distorted curves for all texts and
      headlines.</p>
    design: <a href="http://www.studiohato.com/" target="_blank">Studio Hato</a>
    year: 2015
    font: <a href="/metafonts/bespoke">MF Bespoke</a>
    images:
      - Hato_Staging-disorder-01.jpg
      - Hato_Staging-disorder-02.jpg
      - Hato_Staging-disorder-03.jpg
      - Hato_Staging-disorder-04.jpg
      - Hato_Staging-disorder-05.jpg
      - Hato_Staging-disorder-06.jpg
      - Hato_Staging-disorder-07.jpg
      - Hato_Staging-disorder-08.jpg
      - Hato_Staging-disorder-09.jpg

  yearbook_of_type_1:
    title: Yearbook of Type 1
    description: <p><a
      href="http://www.niggli.ch/en/yearbook-of-type-i-417.html"
      target="_blank">The Yearbook of Type I</a> offers a selection of numerous
      digital typefaces in the form of a printed compendium. Several chapters
      presenting type designers, foundries and background knowledge on
      typography as well as essays provide additional information around the
      field of up to date type design.</p>
    publisher: <a href="http://www.niggli.ch/en/" target="_blank">Niggli</a>
    year: 2013
    font: <a href="/metafonts/bespoke">MF Bespoke</a>
    images:
      - slanted_yearbookoftype1_01.jpg
      - slanted_yearbookoftype1_02.jpg

  dont_shoot_the_messenger:
    title: Don’t Shoot the Messenger
    description: <p>Visual identity for an exhibition about contemporary graphic
      design in Finland at the <a href="http://www.designmuseum.fi/en/"
      target="_blank">Design Museum Helsinki</a>.</p>

      <p><a href="http://www.tsto.org/" target="_blank">Studio Tsto</a> created
      the exhibition design and brochure, following a set of self defined design
      rules. An early version of MF Bespoke underlined their strict design
      approach.</p>
    design: <a href="http://www.tsto.org/" target="_blank">Studio Tsto</a>
    year: 2013
    font: <a href="/metafonts/bespoke">MF Bespoke</a>
    images:
      - Tsto-DontShootTheMessenger_01.jpg
      - Tsto-DontShootTheMessenger_02.jpg
      - Tsto-DontShootTheMessenger_03.jpg
      - Tsto-DontShootTheMessenger_04.jpg
      - Tsto-DontShootTheMessenger_05.jpg
      - Tsto-DontShootTheMessenger_06.jpg
      - Tsto-DontShootTheMessenger_07.jpg
      - Tsto-DontShootTheMessenger_08.jpg

  intreccio_mirage:
    title: Intreccio Mirage
    description: <p>A solo exhibition by artist <a
      href="http://www.43inverness-street.com/exhibitions/milly-thompson/"
      target="_blank">Milly Thompson, Intreccio Mirage</a>, at the 43 Inverness
      Street gallery in London.

      <p>The London based <a href="http://pleasedonotbend.co.uk/"
      target="_blank">Fraser Muggeridge</a> created the exhibition catalogue,
      poster and invitation card for the exhibition, supported by an early
      distorted version of MF Bespoke.</p>

    design: <a href="http://pleasedonotbend.co.uk/" target="_blank">Fraser Muggeridge</a>
    year: 2013
    font: <a href="/metafonts/bespoke">MF Bespoke</a>
    images:
      - Fraser-Muggeridge_Milly_Thompson_01.jpg
      - Fraser-Muggeridge_Milly_Thompson_02.jpg
      - Fraser-Muggeridge_Milly_Thompson_03.jpg
      - Fraser-Muggeridge_Milly_Thompson_04.jpg

  je_peux_le_faire:
    title: Je peux le faire
    description: <p><a href="http://www.lieuxpublics.org/" target="_blank">Je peux le
      faire!</a> is an online project that gathers instructions for
      performative public art, their participants and artists.</p>

      <p>The Bordeaux based design duo <a
      href="http://www.tabaramounien.com/je-peux-le-faire/" target="_blank">Tabaramounien</a>
      created the website, stickers and leaflet, combining a slanted MF Bespoke
      with a late 19th century classicist serif type face.</p>
    design: <a href="http://www.tabaramounien.com/" target="_blank">Tabaramounien</a>
    year: 2016
    font: <a href="/metafonts/bespoke">MF Bespoke</a>
    images:
      - je-peux-le-faire_01.jpg
      - je-peux-le-faire_02.jpg
      - je-peux-le-faire_03.jpg
      - je-peux-le-faire_04.jpg
      - je-peux-le-faire_06.jpg
      - je-peux-le-faire_07.jpg
      - je-peux-le-faire_08.jpg

  die_dada:
    title: Die Dada
    description: <p>The book <a href="http://www.marco-mueller.com/projects/die-dada/" target="_blank">Die
      Dada – Wie Frauen Dada prägten</a> presents for the first time a
      comprehensive overview about the most important She Dada painters,
      writers, dancers, musicians, publishers and patrons of this avant-garde
      art movement.</p>

      <p>Edited by <a href="http://www.inaboesch.ch/de/buecher/die-dada.html" target="_blank">
      Ina Boesch</a> and designed by Marco Müller, with contributions from Ina
      Boesch, Ralf Burmeister, Irene Gammel, Ruth Hemus, Sabine T. Kriebel and
      Walburga Krupp. Published by <a
      href="http://www.scheidegger-spiess.ch/index.php?pd=ss&page=home&view=co&lang=en" target="_blank">Scheidegger
      & Spiess</a> Zurich.</p>

      <p>164 pages, 11 color and 46 greyscale plates, 17 x 24 cm</p>
    design: <a href="http://marco-mueller.com/" target="_blank">Marco Müller</a>
    year: 2015
    font: <a href="/metafonts/bespoke">MF Bespoke</a>
    images:
      - MM_PROJECT_01_001.jpg
      - MM_PROJECT_01_006.jpg
      - MM_PROJECT_01_007.jpg
      - MM_PROJECT_01_009.jpg
      - MM_PROJECT_01_018.jpg
      - MM_PROJECT_01_021.jpg
      - MM_PROJECT_01_024.jpg
      - MM_PROJECT_01_027.jpg

  the_sprawl:
    title: The Sprawl
    description: <p>The film project <a
      href="https://www.youtube.com/watch?v=Bs7NFbE2NS8" target="_blank">The
      Sprawl (Propaganda About Propaganda)</a> from Dutch design studio <a
      href="http://metahaven.net" target="_blank">Metahaven</a> combines facts,
      fantasy, and the internet to dismantle and fight propaganda in today's
      media.</p>

      <p><a href="http://sprawl.space" target="_blank">sprawl.space</a> is the
      online interface for The Sprawl, where the viewer can see the fragments
      that make up the full version of the film. The website has been shaped by
      the interface design of Metahaven, using the viewing algorithms of
      YouTube.</p>

      <p>MF Adjuster (among other typefaces) was used for the website and various medias.</p>
    design: <a href="http://metahaven.net" target="_blank">Metahaven</a>
    year: 2016
    font: <a href="/metafonts/adjuster">MF Adjuster</a>
    images:
      - TheSprawl_Metahaven_01.jpg
      - TheSprawl_Metahaven_02.jpg
      - TheSprawl_Metahaven_03.jpg
      - TheSprawl_Metahaven_04.jpg
      - TheSprawl_Metahaven_05.jpg
      - TheSprawl_Metahaven_06.jpg
      - TheSprawl_Metahaven_08.jpg

  sum_of_parts:
    title: A Sum Of Parts
    description: <p>A visual identity for a collaborative events program
      featuring discussions and workshops, curated by <a
      href="http://www.winchesterstudio.soton.ac.uk/"
      target="_blank">Winchester School of Art</a> at The Archivists Gallery,
      London.</p>

      <p>Marco Müller was asked by the design team of A Sum of Parts for a
      collaboration and provided an early version of a new mono-line METAFONT.
      The output resulted in various pen shapes and drawing modes, that the
      design studio Fourmcreative transformed in a playful variety for online
      and print applications.</p>

      <p>Catalogue, flyers, various promotion materials</p>
    design: <a href="http://fourmcreative.co.uk" target="_blank">Fourmcreative</a>
    year: 2016
    font: MF Calport
    images:
      - ASOP_01.gif
      - ASOP_02.jpg
      - ASOP_03.jpg
      - ASOP_04.jpg
      - ASOP_05.jpg
      - ASOP_08.jpg
      - ASOP_09.jpg
      - ASOP_10.jpg
      - ASOP_11.jpg
      - ASOP_12.jpg
      - ASOP_13.jpg
      - ASOP_14.jpg
      - ASOP_15.jpg
      - ASOP_16.jpg

  eady_forum:
    title: Eady Forum / Extended Times
    description: <p>Both projects were developed at the <a
      href="https://www.rca.ac.uk" target="_blank">Royal College of Art in London</a> using MF
      Bespoke.</p>

      <p><a
      href="http://www.joanapestana.com/index.php?/exhibition/eady-forum/" target="_blank">Eady
      Forum</a> is a platform for discussions about contemporary graphic design
      led by RCA students and supervised by Adrian Shaughnessy. Through a
      series of lectures and events under the title Why so? What if? 2016's
      forum explored the potential for an inquisitive mode of working (why so)
      but also a nonconformist and speculative mode of projecting in design
      (what if).</p

      <p><a
      href="http://www.joanapestana.com/index.php?/projects/the-extended-times/" target="_blank">The
      Extended Times</a>, developed by London-Porto based designer <a
      href="http://intern-mag.com/joana-pestana/" target="_blank">Joana Pestana</a> during her
      MA, is a fictional newspaper dealing with life extension and digital
      afterlife. It speculates about the possible consequences of graphical
      user interfaces that allude to perpetual progress and continuity.</p>

      <p>Website, screen printed posters, newspaper, various media</p>
    design: <a href="http://cargocollective.com/joanapestana" target="_blank">Joana Pestana</a>
    year: 2016
    font: <a href="/metafonts/bespoke">MF Bespoke</a>
    images:
      - EadyForum_01.jpg
      - EadyForum_02.jpg
      - EadyForum_03.jpg
      - EadyForum_04.jpg
      - EadyForum_05.jpg
      - EadyForum_08.jpg
      - EadyForum_JoanaPestana-ExtendedTimes_1.jpg
      - EadyForum_JoanaPestana-ExtendedTimes_3.jpg
      - EadyForum_JoanaPestana-ExtendedTimes_4.jpg

  meshtivism:
    title: Meshtivism
    description: <p><a
      href="https://www.behance.net/gallery/41101975/Meshtivism" target="_blank">Meshtivism</a>
      by Stockholm based designer and illustrator <a
      href="http://erikkirtley.com" target="_blank">Erik Kirtley</a> is a speculative manual
      manifesto from a near future in which digital activists avoid the
      commercialized and surveillance network we know as the internet. They
      organize and collaborate via so called mesh networks instead, built and
      maintained by themselves.</p>

      <p>Typefaces used in the publication include an early version of IP by
      William Andersson and versions of MF Bespoke.</p>
    design: <a href="http://erikkirtley.com" target="_blank">Erik Kirtley</a>
    year: 2016
    font: <a href="/metafonts/bespoke">MF Bespoke</a>
    images:
      - Meshtivism_01.jpg
      - Meshtivism_02.jpg
      - Meshtivism_03.jpg
      - Meshtivism_04.jpg
      - Meshtivism_05.jpg
      - Meshtivism_06.jpg

  form_informed:
    title: Form Informed
    description: <p><a href="http://www.maurabiava.com" target="_blank">Maura
      Biava</a> combines in her artist’s book <a
      href="http://www.meeusontwerpt.nl/2016_form_informed.php"
      target="_blank">Form Informed</a> two-dimensional mathematical graphs
      with strange, new and compelling three-dimensional forms.</p>

      <p>The book was published by <a href="http://www.konnotation.com"
      target="_blank">Konnotation</a>, designed by Amsterdam based designers
      Hilde en Janna Meeus and printed at the <a
      href="http://www.janvaneyck.nl/en/labs/charles-nypels-lab/"
      target="_blank">Charles Nypels Lab Van Eyck Academie</a> during the
      Magical Riso seminar.</p>

      <p>60 pages, Risograph printed in 10 colors, 20 x 29 cm</p>

    design: <a href="http://www.meeusontwerpt.nl" target="_blank">Hilde en Janna Meeus</a>
    year: 2016
    font: <a href="/metafonts/bespoke">MF Bespoke</a>
    images:
      - FORM_INFORMED_01.jpg
      - FORM_INFORMED_02.jpg
      - FORM_INFORMED_03.jpg
      - FORM_INFORMED_04.jpg
      - FORM_INFORMED_05.jpg
      - FORM_INFORMED_06.jpg
      - FORM_INFORMED_07.jpg

  tradeptford:
    title: Tradeptford
    description: <p>For 6 months the project explored local identity,
      gentrification and the role of the citizens in Deptford, South East
      London.</p>

      <p><a href="http://www.tradeptford.co.uk" target="_blank">Tradeptford</a>
      provided a local platform hosting events and debates. It aimed for a new
      typology of market forum which would turn the artist/architect into a
      lever for positive social change. Through the direct participation in
      each forum, local residents worked together with local artists and
      designers to unpick the impact of gentrification in Deptford.</p>

      <p>The identity designed by London based designer <a
      href="http://rossbennett.eu/tradeptford" target="_blank">Ross Bennett</a>
      is based on Enzo Mari's table structures which formed the foundation and
      surface for the workshop lunches and debates, using a custom MF
      Bespoke.</p>

      <p>Leaflets, posters, website</p>

    design: <a href="http://rossbennett.eu/" target="_blank">Ross Bennett</a>
    year: 2016
    font: <a href="/metafonts/bespoke">MF Bespoke</a>
    images:
      - Deptford_00.jpg
      - Deptford_01.jpg
      - Deptford_02.jpg
      - Deptford_03.jpg
      - Deptford_04.jpg
      - Deptford_05.jpg
      - Deptford_06.jpg
      - Deptford_07.jpg
      - Deptford_08.jpg
      - Deptford_09.jpg
      - Deptford_10.jpg
