showcases:
  off_grid:
    title: Off Grid
    description: <p>The Glasgow based Warriors Studio used MF Bespoke for the
      visual identity, poster and printed catalogue design for an
      interdisciplinary artists and graphic designers exhibition in their home
      town.</p>
      <p>The exhibition was originally shown at South Block Glasgow as part of <a
      href="http://graphicdesignfestivalscotland.com" target="_blank">Graphic
      Design Festival Scotland</a> 2015 before being invited to Nancy, France,
      where it was shown at <a href="http://mymonkey.fr"
      target="_blank">Galerie My Monkey</a> – a highly commended graphic design
      gallery, which has hosted exhibitions over the past 12 years.</p>
    agency: <a href="http://warriorsstudio.com" target="_blank">Warriors Studio</a>
    year: 2015
    font: <a href="/metafonts/bespoke">MF Bespoke</a>
    images:
      -
        - warriors-studio-off-grid_01.jpg
        -
      -
        - warriors-studio-off-grid_02.jpg
        -
      -
        - warriors-studio-off-grid_03.jpg
        -
      -
        - warriors-studio-off-grid_04.jpg
        -
      -
        - warriors-studio-off-grid_05.jpg
        -
      -
        - warriors-studio-off-grid_06.jpg
        -
      -
        - warriors-studio-off-grid_07.jpg
        -
      -
        - warriors-studio-off-grid_08.jpg
        -
      -
        - warriors-studio-off-grid_09.jpg
        -
